// ============================================================
// BRIEF ARTISAN — Données mock
// 8 briefs à différents statuts pour tester tous les parcours
// ============================================================

import type { BriefArtisan } from './types';

export const MOCK_BRIEFS: BriefArtisan[] = [
  // 1. Brouillon
  {
    id: 'BRA-000001',
    title: 'Lampe Abat-jour Bogolan',
    description: 'Lampe sur pied avec abat-jour en tissu bogolan teint main.',
    category: 'Luminaires',
    zone: 'Ouidah',
    piece: 'Salon',
    style: 'Ethnique chic',
    dimensions: 'Ø 35 x H 45 cm',
    materials: ['Tissu bogolan', 'Métal'],
    budgetMin: 40000,
    budgetMax: 80000,
    inspirations: [],
    status: 'DRAFT',
    createdAt: '2026-06-25T10:00:00Z',
    updatedAt: '2026-06-25T10:00:00Z',
    proposals: [],
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 2. Publié (en attente de propositions)
  {
    id: 'BRA-000002',
    title: 'Table basse ronde en rotin',
    description: 'Table basse ronde, plateau en rotin tressé, structure en bois.',
    category: 'Tables',
    zone: 'Cotonou',
    piece: 'Salon',
    style: 'Naturel bohème',
    dimensions: 'Ø 80 x H 40 cm',
    materials: ['Rotin', 'Bois local'],
    budgetMin: 60000,
    budgetMax: 120000,
    inspirations: [],
    status: 'PUBLISHED',
    createdAt: '2026-06-20T10:00:00Z',
    updatedAt: '2026-06-20T10:00:00Z',
    expiresAt: '2026-07-04T10:00:00Z',
    proposals: [],
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 3. 3 propositions reçues
  {
    id: 'BRA-000003',
    title: 'Dressing sur mesure chambre',
    description: 'Dressing en bois massif, 3 portes coulissantes, finition vernis naturel.',
    category: 'Rangements',
    zone: 'Cotonou',
    piece: 'Chambre',
    style: 'Moderne épuré',
    dimensions: 'L 300 x H 240 x P 60 cm',
    materials: ['Bois iroko', 'Vernis naturel'],
    budgetMin: 150000,
    budgetMax: 300000,
    inspirations: [],
    status: 'PROPOSALS_RECEIVED',
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-19T10:00:00Z',
    proposals: [
      {
        id: 'BAP-000001',
        briefId: 'BRA-000003',
        artisanId: 'ART-000001',
        artisanName: 'Kofi Akindélé',
        artisanAvatar: 'https://images.unsplash.com/photo-1614023342667-6f060e9d1e04?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N3',
        artisanVerified: true,
        price: 220000,
        deliveryTime: '18 jours',
        materials: 'Bois massif iroko, vernis naturel',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        message: 'Bois iroko de qualité supérieure, vernis écologique.',
        submittedAt: '2026-06-17T10:00:00Z',
      },
      {
        id: 'BAP-000002',
        briefId: 'BRA-000003',
        artisanId: 'ART-000002',
        artisanName: 'Brice Gogan',
        artisanAvatar: 'https://images.unsplash.com/photo-1620932934088-fbdb2920e484?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N2',
        artisanVerified: true,
        price: 195000,
        deliveryTime: '21 jours',
        materials: 'Contreplaqué bouleau, peinture éco-responsable',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        message: 'Solution économique avec contreplaqué bouleau.',
        submittedAt: '2026-06-18T10:00:00Z',
      },
      {
        id: 'BAP-000003',
        briefId: 'BRA-000003',
        artisanId: 'ART-000003',
        artisanName: 'Emile Agossou',
        artisanAvatar: 'https://images.unsplash.com/photo-1509099863731-ef4bff19e808?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N1',
        artisanVerified: false,
        price: 165000,
        deliveryTime: '25 jours',
        materials: 'Médjin (bois local), finition cire d\'abeille',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        message: 'Bois local médjin, finition traditionnelle cire d\'abeille.',
        submittedAt: '2026-06-19T10:00:00Z',
      },
    ],
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 4. En discussion
  {
    id: 'BRA-000004',
    title: 'Étagère murale bois de rose',
    description: 'Étagère murale en bois de rose, 5 niveaux, fixation invisible.',
    category: 'Rangements',
    zone: 'Cotonou',
    piece: 'Bureau',
    style: 'Minimaliste',
    dimensions: 'L 120 x H 180 x P 25 cm',
    materials: ['Bois de rose'],
    budgetMin: 80000,
    budgetMax: 150000,
    inspirations: [],
    status: 'IN_DISCUSSION',
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-06-22T10:00:00Z',
    proposals: [
      {
        id: 'BAP-000004',
        briefId: 'BRA-000004',
        artisanId: 'ART-000004',
        artisanName: 'Atelier Kossi',
        artisanAvatar: 'https://images.unsplash.com/photo-1614023342667-6f060e9d1e04?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N3',
        artisanVerified: true,
        price: 120000,
        deliveryTime: '15 jours',
        materials: 'Bois de rose local, huile naturelle',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        submittedAt: '2026-06-12T10:00:00Z',
      },
    ],
    selectedProposalId: 'BAP-000004',
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 5. Artisan sélectionné (en attente de confirmation)
  {
    id: 'BRA-000005',
    title: 'Fauteuil Sahel Tressé',
    description: 'Fauteuil en rotin tressé, structure bois iroko, coussin coton wax.',
    category: 'Sièges',
    zone: 'Parakou',
    piece: 'Salon',
    style: 'Sahel contemporain',
    dimensions: '85 x 90 x 75 cm',
    materials: ['Rotin naturel', 'Bois iroko', 'Coton wax'],
    budgetMin: 200000,
    budgetMax: 280000,
    inspirations: [],
    status: 'ARTISAN_SELECTED',
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-06-22T10:00:00Z',
    proposals: [
      {
        id: 'BAP-000005',
        briefId: 'BRA-000005',
        artisanId: 'ART-000004',
        artisanName: 'Atelier Kossi',
        artisanAvatar: 'https://images.unsplash.com/photo-1614023342667-6f060e9d1e04?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N3',
        artisanVerified: true,
        price: 245000,
        deliveryTime: '18 jours',
        materials: 'Rotin naturel, bois iroko, coton wax',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        submittedAt: '2026-06-12T10:00:00Z',
      },
    ],
    selectedProposalId: 'BAP-000005',
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 6. Paiement à effectuer (AWAITING_DEPOSIT)
  {
    id: 'BRA-000006',
    title: 'Table basse sur mesure',
    description: 'Table basse en bois massif avec plateau marqueterie.',
    category: 'Tables',
    zone: 'Cotonou',
    piece: 'Salon',
    style: 'Contemporain',
    dimensions: 'L 120 x l 60 x H 40 cm',
    materials: ['Bois iroko', 'Marqueterie'],
    budgetMin: 100000,
    budgetMax: 200000,
    inspirations: [],
    status: 'AWAITING_DEPOSIT',
    createdAt: '2026-06-05T10:00:00Z',
    updatedAt: '2026-06-22T10:00:00Z',
    proposals: [
      {
        id: 'BAP-000006',
        briefId: 'BRA-000006',
        artisanId: 'ART-000004',
        artisanName: 'Atelier Kossi',
        artisanAvatar: 'https://images.unsplash.com/photo-1614023342667-6f060e9d1e04?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N3',
        artisanVerified: true,
        price: 185000,
        deliveryTime: '18 jours',
        materials: 'Bois iroko massif, marqueterie laiton',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        submittedAt: '2026-06-07T10:00:00Z',
      },
    ],
    selectedProposalId: 'BAP-000006',
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 7. Converti en projet
  {
    id: 'BRA-000007',
    title: 'Canapé personnalisé Cotonou',
    description: 'Canapé 3 places en bois massif iroko, tissu coton wax.',
    category: 'Sièges',
    zone: 'Cotonou',
    piece: 'Salon',
    style: 'Contemporain africain',
    dimensions: '220 x 95 x 85 cm',
    materials: ['Bois iroko', 'Coton wax', 'Mousse haute résilience'],
    budgetMin: 300000,
    budgetMax: 500000,
    inspirations: [],
    status: 'CONVERTED_TO_PROJECT',
    createdAt: '2026-05-05T10:00:00Z',
    updatedAt: '2026-06-10T10:00:00Z',
    proposals: [
      {
        id: 'BAP-000007',
        briefId: 'BRA-000007',
        artisanId: 'ART-000004',
        artisanName: 'Atelier Kossi',
        artisanAvatar: 'https://images.unsplash.com/photo-1614023342667-6f060e9d1e04?auto=format&fit=crop&w=400&q=85',
        artisanLevel: 'N3',
        artisanVerified: true,
        price: 420000,
        deliveryTime: '4 semaines',
        materials: 'Bois massif iroko, tissu coton wax, mousse haute résilience',
        images: [],
        paymentConditions: 'Paiement sécurisé Mobile Money',
        submittedAt: '2026-05-07T10:00:00Z',
      },
    ],
    selectedProposalId: 'BAP-000007',
    linkedProjectId: 'PRA-000001',
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
  // 8. Expiré
  {
    id: 'BRA-000008',
    title: 'Tabouret Tamtam x2',
    description: 'Deux tabourets tamtam en bois iroko, tissu wax.',
    category: 'Sièges',
    zone: 'Cotonou',
    piece: 'Salon',
    style: 'Traditionnel moderne',
    dimensions: 'Ø 40 x H 45 cm (x2)',
    materials: ['Bois iroko', 'Coton wax'],
    budgetMin: 50000,
    budgetMax: 100000,
    inspirations: [],
    status: 'EXPIRED',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
    expiresAt: '2026-05-15T10:00:00Z',
    proposals: [],
    clientId: 'CL-001',
    clientName: 'Sophie Kossou',
    history: [],
    modifications: [],
  },
];
